services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  Faeb\Videoprocessing\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Faeb\Videoprocessing\EventListener\FileProcessingEvent:
    tags:
      - name: event.listener
        identifier: 'FileProcessingEvent'

  Faeb\Videoprocessing\EventListener\EnrichFileMetaDataEvent:
    tags:
      - name: event.listener
        identifier: 'EnrichFileMetaDataEvent'

  Faeb\Videoprocessing\Command\Process:
    tags:
      -
        name: console.command
        command: 'video:process'
        description: '[Fäb] process all open video processing tasks'
        schedulable: true
