services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  Faeb\Videoprocessing\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Faeb\Videoprocessing\ViewHelpers\ProgressEid:
    public: true


  # Image File (for Videos)
  Faeb\Videoprocessing\EventListener\ImageFileProcessingEvent:
    tags:
      - name: event.listener
        # identifier: 'BeforeFileProcessingEvent'
        identifier: 'AfterFileProcessingEvent'

  # Video File, two separate Event Listeners?
  Faeb\Videoprocessing\EventListener\VideoFileProcessingEvent:
    tags:
      - name: event.listener
        identifier: 'AfterFileAddedToIndexEvent'


  Faeb\Videoprocessing\EventListener\EnrichFileMetaDataEvent:
    tags:
      - name: event.listener
        identifier: 'EnrichFileMetaDataEvent'

  Faeb\Videoprocessing\EventListener\AfterFileMetaDataUpdatedEvent:
    tags:
      - name: event.listener
        identifier: 'AfterFileMetaDataUpdatedEvent'

  Faeb\Videoprocessing\EventListener\AfterFileMetaDataCreatedEvent:
    tags:
      - name: event.listener
        identifier: 'AfterFileMetaDataCreatedEvent'

  Faeb\Videoprocessing\Command\Process:
    tags:
      -
        name: console.command
        command: 'video:process'
        description: 'process all open video processing tasks'
        schedulable: true
