services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  Faeb\Videoprocessing\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Faeb\Videoprocessing\ViewHelpers\ProgressEid:
    public: true

  Faeb\Videoprocessing\ViewHelpers\FrameViewHelper:
    autowire: true
    autoconfigure: true
    public: true

# Poster Image File (from Videos)
#  Faeb\Videoprocessing\EventListener\ImageFileProcessingEvent:
#    tags:
#      - name: event.listener
#        identifier: 'BeforeFileProcessingEvent'
#        # identifier: 'AfterFileProcessingEvent'
#        # identifier: 'AfterFileAddedEvent'

  # Video File, two separate Event Listeners!
  Faeb\Videoprocessing\EventListener\VideoFileProcessingEvent:
    tags:
      - name: event.listener
        #identifier: 'AfterFileProcessingEvent'
        # identifier: 'AfterFileAddedToIndexEvent'
        identifier: 'BeforeFileProcessingEvent'
        #before: 'BeforeFileProcessingEvent'

  Faeb\Videoprocessing\EventListener\EnrichFileMetaDataEvent:
    tags:
      - name: event.listener
        identifier: 'EnrichFileMetaDataEvent'

  Faeb\Videoprocessing\EventListener\AfterFileMetaDataUpdatedEvent:
    tags:
      - name: event.listener
        identifier: 'AfterFileMetaDataUpdatedEvent'

  Faeb\Videoprocessing\EventListener\AfterFileMetaDataCreatedEvent:
    tags:
      - name: event.listener
        identifier: 'AfterFileMetaDataCreatedEvent'

  Faeb\Videoprocessing\Command\Process:
    tags:
      -
        name: console.command
        command: 'video:process'
        description: 'process all open video processing tasks'
        schedulable: true
